name: ci-tethys-store-test
on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md
            - CHANGELOG.md # Should never be edited anyway
            - .gitignore
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Setup
              run: yarn --frozen-lockfile

            - name: Test
              run: |
                  yarn lint
                  yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI
                  yarn run report-coverage
