name: ci-tethys-store-test
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-
            - run: yarn --frozen-lockfile
            - name: Setup
              run: yarn

            - name: Test
              run: |
                  npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
                  npm run report-coverage
