name: ci-tethys-store-test
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Setup
              run: yarn --frozen-lockfile

            - name: Test
              run: |
                  yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
                  yarn run report-coverage
